# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
